version: '3.8'
services:
  todoapp:
    container_name: todoapp
    image: ${DOCKER_REGISTRY-}todoapp/todo
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - '.:/app'
      - '/app/node_modules'
      - '/app/.next'
