import TodoLayout from "@/components/TodoLayout";
import Head from "next/head";
import { FC } from "react";

const Home: FC = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TodoLayout />
      </main>
    </>
  );
};

export default Home;
